from typing import Any

fpl_player_data: dict[str, Any] = {
    "table_name": "fpl_player_data",
    "table_column_configs": [
        {
            "column_name": "fpl_player_id",
            "column_type": "VARCHAR (255)",
            "primary_key": True,
        },
        {
            "column_name": "chance_of_playing_next_round",
            "column_type": "INT",
            "not_null": True,
        },
        {
            "column_name": "chance_of_playing_this_round",
            "column_type": "INT",
            "not_null": True,
        },
        {"column_name": "code", "column_type": "INT", "not_null": True},
        {"column_name": "cost_change_event", "column_type": "INT", "not_null": True},
        {
            "column_name": "cost_change_event_fall",
            "column_type": "INT",
            "not_null": True,
        },
        {"column_name": "cost_change_start", "column_type": "INT", "not_null": True},
        {
            "column_name": "cost_change_start_fall",
            "column_type": "INT",
            "not_null": True,
        },
        {"column_name": "dreamteam_count", "column_type": "INT", "not_null": True},
        {"column_name": "element_type", "column_type": "INT", "not_null": True},
        {"column_name": "ep_next", "column_type": "VARCHAR (255)", "not_null": True},
        {"column_name": "ep_this", "column_type": "VARCHAR (255)", "not_null": True},
        {"column_name": "event_points", "column_type": "INT", "not_null": True},
        {"column_name": "first_name", "column_type": "VARCHAR (255)", "not_null": True},
        {"column_name": "form", "column_type": "VARCHAR (255)", "not_null": True},
        {"column_name": "id", "column_type": "INT", "not_null": True},
        {"column_name": "in_dreamteam", "column_type": "BOOLEAN", "not_null": True},
        {"column_name": "news", "column_type": "VARCHAR (255)", "not_null": True},
        {"column_name": "news_added", "column_type": "VARCHAR (255)", "not_null": True},
        {"column_name": "now_cost", "column_type": "INT", "not_null": True},
        {"column_name": "photo", "column_type": "VARCHAR (255)", "not_null": True},
        {
            "column_name": "points_per_game",
            "column_type": "VARCHAR (255)",
            "not_null": True,
        },
        {
            "column_name": "second_name",
            "column_type": "VARCHAR (255)",
            "not_null": True,
        },
        {
            "column_name": "selected_by_percent",
            "column_type": "VARCHAR (255)",
            "not_null": True,
        },
        {"column_name": "special", "column_type": "BOOLEAN", "not_null": True},
        {"column_name": "squad_number", "column_type": "INT", "not_null": True},
        {"column_name": "status", "column_type": "VARCHAR (255)", "not_null": True},
        {"column_name": "team", "column_type": "INT", "not_null": True},
        {"column_name": "team_code", "column_type": "INT", "not_null": True},
        {"column_name": "total_points", "column_type": "INT", "not_null": True},
        {"column_name": "transfers_in", "column_type": "INT", "not_null": True},
        {"column_name": "transfers_in_event", "column_type": "INT", "not_null": True},
        {"column_name": "transfers_out", "column_type": "INT", "not_null": True},
        {"column_name": "transfers_out_event", "column_type": "INT", "not_null": True},
        {"column_name": "value_form", "column_type": "VARCHAR (255)", "not_null": True},
        {
            "column_name": "value_season",
            "column_type": "VARCHAR (255)",
            "not_null": True,
        },
        {"column_name": "web_name", "column_type": "VARCHAR (255)", "not_null": True},
        {"column_name": "region", "column_type": "INT", "not_null": True},
        {"column_name": "minutes", "column_type": "INT", "not_null": True},
        {"column_name": "goals_scored", "column_type": "INT", "not_null": True},
        {"column_name": "assists", "column_type": "INT", "not_null": True},
        {"column_name": "clean_sheets", "column_type": "INT", "not_null": True},
        {"column_name": "goals_conceded", "column_type": "INT", "not_null": True},
        {"column_name": "own_goals", "column_type": "INT", "not_null": True},
        {"column_name": "penalties_saved", "column_type": "INT", "not_null": True},
        {"column_name": "penalties_missed", "column_type": "INT", "not_null": True},
        {"column_name": "yellow_cards", "column_type": "INT", "not_null": True},
        {"column_name": "red_cards", "column_type": "INT", "not_null": True},
        {"column_name": "saves", "column_type": "INT", "not_null": True},
        {"column_name": "bonus", "column_type": "INT", "not_null": True},
        {"column_name": "bps", "column_type": "INT", "not_null": True},
        {"column_name": "influence", "column_type": "VARCHAR (255)", "not_null": True},
        {"column_name": "creativity", "column_type": "VARCHAR (255)", "not_null": True},
        {"column_name": "threat", "column_type": "INT", "not_null": True},
        {"column_name": "ict_index", "column_type": "VARCHAR (255)", "not_null": True},
        {"column_name": "starts", "column_type": "INT", "not_null": True},
        {
            "column_name": "expected_goals",
            "column_type": "VARCHAR (255)",
            "not_null": True,
        },
        {
            "column_name": "expected_assists",
            "column_type": "VARCHAR (255)",
            "not_null": True,
        },
        {
            "column_name": "expected_goal_involvements",
            "column_type": "VARCHAR (255)",
            "not_null": True,
        },
        {
            "column_name": "expected_goals_conceded",
            "column_type": "VARCHAR (255)",
            "not_null": True,
        },
        {"column_name": "influence_rank", "column_type": "INT", "not_null": True},
        {"column_name": "influence_rank_type", "column_type": "INT", "not_null": True},
        {"column_name": "creativity_rank", "column_type": "INT", "not_null": True},
        {"column_name": "creativity_rank_type", "column_type": "INT", "not_null": True},
        {"column_name": "threat_rank", "column_type": "INT", "not_null": True},
        {"column_name": "threat_rank_type", "column_type": "INT", "not_null": True},
        {"column_name": "ict_index_rank", "column_type": "INT", "not_null": True},
        {"column_name": "ict_index_rank_type", "column_type": "INT", "not_null": True},
        {
            "column_name": "corners_and_indirect_freekicks_order",
            "column_type": "INT",
            "not_null": True,
        },
        {
            "column_name": "corners_and_indirect_freekicks_text",
            "column_type": "INT",
            "not_null": True,
        },
        {
            "column_name": "direct_freekicks_order",
            "column_type": "INT",
            "not_null": True,
        },
        {
            "column_name": "direct_freekicks_text",
            "column_type": "INT",
            "not_null": True,
        },
        {"column_name": "penalties_order", "column_type": "INT", "not_null": True},
        {"column_name": "penalties_text", "column_type": "INT", "not_null": True},
        {
            "column_name": "expected_goals_per_90",
            "column_type": "VARCHAR (255)",
            "not_null": True,
        },
        {
            "column_name": "saves_per_90",
            "column_type": "VARCHAR (255)",
            "not_null": True,
        },
        {
            "column_name": "expected_assists_per_90",
            "column_type": "VARCHAR (255)",
            "not_null": True,
        },
        {
            "column_name": "expected_goal_involvements_per_90",
            "column_type": "VARCHAR (255)",
            "not_null": True,
        },
        {
            "column_name": "expected_goals_conceded_per_90",
            "column_type": "VARCHAR (255)",
            "not_null": True,
        },
        {
            "column_name": "goals_conceded_per_90",
            "column_type": "VARCHAR (255)",
            "not_null": True,
        },
        {"column_name": "now_cost_rank", "column_type": "INT", "not_null": True},
        {"column_name": "now_cost_rank_type", "column_type": "INT", "not_null": True},
        {"column_name": "form_rank", "column_type": "INT", "not_null": True},
        {"column_name": "form_rank_type", "column_type": "INT", "not_null": True},
        {"column_name": "points_per_game_rank", "column_type": "INT", "not_null": True},
        {
            "column_name": "points_per_game_rank_type",
            "column_type": "INT",
            "not_null": True,
        },
        {"column_name": "selected_rank", "column_type": "INT", "not_null": True},
        {"column_name": "selected_rank_type", "column_type": "INT", "not_null": True},
        {
            "column_name": "starts_per_90",
            "column_type": "VARCHAR (255)",
            "not_null": True,
        },
        {
            "column_name": "clean_sheets_per_90",
            "column_type": "VARCHAR (255)",
            "not_null": True,
        },
        {
            "column_name": "fbref_team_name",
            "column_type": "VARCHAR (255)",
            "not_null": True,
        },
    ],
}
