from typing import Any

fpl_player_gameweek_data: dict[str, Any] = {
    "table_name": "fpl_player_gameweek_data",
    "table_column_configs": [
        {
            "column_name": "fpl_player_gameweek_id",
            "column_type": "VARCHAR (255)",
            "primary_key": True,
        },
        {
            "column_name": "fpl_player_id",
            "column_type": "VARCHAR (255)",
            "not_null": True,
        },
        {
            "column_name": "fpl_match_date",
            "column_type": "VARCHAR (255)",
            "not_null": True,
        },
        {"column_name": "element", "column_type": "INT", "not_null": True},
        {"column_name": "fixture", "column_type": "INT", "not_null": True},
        {"column_name": "opponent_team", "column_type": "INT", "not_null": True},
        {"column_name": "total_points", "column_type": "INT", "not_null": True},
        {"column_name": "was_home", "column_type": "BOOLEAN", "not_null": True},
        {
            "column_name": "kickoff_time",
            "column_type": "VARCHAR(255)",
            "not_null": True,
        },
        {"column_name": "team_h_score", "column_type": "INT", "not_null": True},
        {"column_name": "team_a_score", "column_type": "INT", "not_null": True},
        {"column_name": "round", "column_type": "INT", "not_null": True},
        {"column_name": "modified", "column_type": "BOOLEAN", "not_null": True},
        {"column_name": "minutes", "column_type": "INT", "not_null": True},
        {"column_name": "goals_scored", "column_type": "INT", "not_null": True},
        {"column_name": "assists", "column_type": "INT", "not_null": True},
        {"column_name": "clean_sheets", "column_type": "INT", "not_null": True},
        {"column_name": "goals_conceded", "column_type": "INT", "not_null": True},
        {"column_name": "own_goals", "column_type": "INT", "not_null": True},
        {"column_name": "penalties_saved", "column_type": "INT", "not_null": True},
        {"column_name": "penalties_missed", "column_type": "INT", "not_null": True},
        {"column_name": "yellow_cards", "column_type": "INT", "not_null": True},
        {"column_name": "red_cards", "column_type": "INT", "not_null": True},
        {"column_name": "saves", "column_type": "INT", "not_null": True},
        {"column_name": "bonus", "column_type": "INT", "not_null": True},
        {"column_name": "bps", "column_type": "INT", "not_null": True},
        {"column_name": "influence", "column_type": "VARCHAR(255)", "not_null": True},
        {"column_name": "creativity", "column_type": "VARCHAR(255)", "not_null": True},
        {"column_name": "threat", "column_type": "VARCHAR(255)", "not_null": True},
        {"column_name": "ict_index", "column_type": "VARCHAR(255)", "not_null": True},
        {"column_name": "starts", "column_type": "INT", "not_null": True},
        {
            "column_name": "expected_goals",
            "column_type": "VARCHAR(255)",
            "not_null": True,
        },
        {
            "column_name": "expected_assists",
            "column_type": "VARCHAR(255)",
            "not_null": True,
        },
        {
            "column_name": "expected_goal_involvements",
            "column_type": "VARCHAR(255)",
            "not_null": True,
        },
        {
            "column_name": "expected_goals_conceded",
            "column_type": "VARCHAR(255)",
            "not_null": True,
        },
        {
            "column_name": "clearances_blocks_interceptions",
            "column_type": "INT",
            "not_null": True,
        },
        {
            "column_name": "recoveries",
            "column_type": "INT",
            "not_null": True,
        },
        {
            "column_name": "tackles",
            "column_type": "INT",
            "not_null": True,
        },
        {
            "column_name": "defensive_contribution",
            "column_type": "INT",
            "not_null": True,
        },
        {"column_name": "value", "column_type": "INT", "not_null": True},
        {"column_name": "transfers_balance", "column_type": "INT", "not_null": True},
        {"column_name": "selected", "column_type": "INT", "not_null": True},
        {"column_name": "transfers_in", "column_type": "INT", "not_null": True},
        {"column_name": "transfers_out", "column_type": "INT", "not_null": True},
    ],
}
