fbref_team_overall = {
    "team": {"type": "str", "sql": "team VARCHAR (255) PRIMARY KEY"},
    "team_url": {"type": "str", "sql": "team_url VARCHAR (255) NOT NULL"},
    "games": {"type": "int", "sql": "games INT NOT NULL"},
    "wins": {"type": "int", "sql": "wins INT NOT NULL"},
    "ties": {"type": "int", "sql": "ties INT NOT NULL"},
    "losses": {"type": "int", "sql": "losses INT NOT NULL"},
    "goals_for": {"type": "int", "sql": "goals_for INT NOT NULL"},
    "goals_against": {"type": "int", "sql": "goals_against INT NOT NULL"},
    "goal_diff": {"type": "int", "sql": "goal_diff INT NOT NULL"},
    "points": {"type": "int", "sql": "points INT NOT NULL"},
    "points_avg": {"type": "float", "sql": "points_avg DECIMAL NOT NULL"},
    "xg_for": {"type": "float", "sql": "xg_for DECIMAL NOT NULL"},
    "xg_against": {"type": "float", "sql": "xg_against DECIMAL NOT NULL"},
    "xg_diff": {"type": "float", "sql": "xg_diff DECIMAL NOT NULL"},
    "xg_diff_per90": {"type": "float", "sql": "xg_diff_per90 DECIMAL NOT NULL"},
    "attendance_per_g": {"type": "int", "sql": "attendance_per_g INT NOT NULL"},
    "top_team_scorers": {
        "type": "str",
        "sql": "top_team_scorers VARCHAR (255) NOT NULL",
    },
    "top_team_scorers_url": {
        "type": "str",
        "sql": "top_team_scorers_url VARCHAR (255) NOT NULL",
    },
    "top_keeper": {"type": "str", "sql": "top_keeper VARCHAR (255) NOT NULL"},
    "top_keeper_url": {"type": "str", "sql": "top_keeper_url VARCHAR (255) NOT NULL"},
    "notes": {"type": "str", "sql": "notes VARCHAR (255) NOT NULL"},
}
