fbref_team_overall_data_types = {
    "team": "str",
    "team_url": "str",
    "games": "int",
    "wins": "int",
    "ties": "int",
    "losses": "int",
    "goals_for": "int",
    "goals_against": "int",
    "goal_diff": "int",
    "points": "int",
    "points_avg": "float",
    "xg_for": "float",
    "xg_against": "float",
    "xg_diff": "float",
    "xg_diff_per90": "float",
    "attendance_per_g": "int",
    "top_team_scorers": "str",
    "top_team_scorers_url": "str",
    "top_keeper": "str",
    "top_keeper_url": "str",
    "notes": "str",
}
